apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    type: payment-api
spec:
  replicas: 1
  selector:
    matchLabels:
      type: payment-api
  minReadySeconds: 1
  progressDeadlineSeconds: 60
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        type: payment-api
    spec:
      containers:
        - name: payment
          image: tinjis-paymentsvc
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /rest/health
              port: 8080
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /rest/health
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: payment-svc
#  labels:
#    type: core-api
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080
  selector:
    type: payment-api